# Generated by Django 5.2.3 on 2025-07-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='recieved',
            field=models.BooleanField(default=False),
        ),
    ]
