# Generated by Django 5.2.3 on 2025-07-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0002_scholarship_recieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='amount',
            field=models.TextField(default=0),
        ),
    ]
