# Generated by Django 5.2.3 on 2025-07-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0003_scholarship_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='recieved',
            field=models.BooleanField(null=True),
        ),
    ]
