# Generated by Django 5.2.3 on 2025-07-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0004_alter_scholarship_recieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='requirements',
            field=models.TextField(default='None'),
        ),
    ]
