# Generated by Django 5.2.3 on 2025-07-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0006_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
